	.align 2
voicegroup274:: @ bw soundlist
	voice_keysplit voicegroupInst1, KeySplitTable90	@ grand piano
	voice_keysplit voicegroupInst2, KeySplitTable36	@ tack piano
	voice_keysplit voicegroup235, KeySplitTable75	@ piano octave
	voice_keysplit voicegroupInst3, KeySplitTable36	@ rhodes (115 rel)
	voice_keysplit voicegroupInst4, KeySplitTable36	@ rhodes (125 rel)
	voice_keysplit voicegroup234, KeySplitTable36	@ rock piano
	voice_keysplit voicegroupInst5, KeySplitTable81	@ harpsichord
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst6, KeySplitTable83	@ vibraphone
	voice_keysplit voicegroupInst7, KeySplitTable94	@ marimba
	voice_keysplit voicegroupInst8, KeySplitTable53	@ xylophone 1
	voice_keysplit voicegroupInst9, KeySplitTable53	@ xylophone 2
	voice_keysplit voicegroupInst10, KeySplitTable25	@ tubular bell
	voice_keysplit voicegroupInst11, KeySplitTable94	@ glockenspiel
	voice_keysplit voicegroup243, KeySplitTable83	@ music box
	voice_keysplit voicegroupInst12, KeySplitTable79	@ drawbar organ
	voice_keysplit voicegroupInst13, KeySplitTable79	@ jazz organ
	voice_keysplit voicegroupInst14, KeySplitTable79	@ accordion
	voice_keysplit voicegroupInst15, KeySplitTable87	@ nylon string guitar
	voice_keysplit voicegroup248, KeySplitTable41	@ folk guitar
	voice_keysplit voicegroupInst16, KeySplitTable73	@ marschall guitar (125 rel)
	voice_keysplit voicegroupInst17, KeySplitTable73	@ marschall guitar (120 rel)
	voice_keysplit voicegroupInst18, KeySplitTable41	@ clean guitar
	voice_keysplit voicegroupInst19, KeySplitTable54	@ upright bass
	voice_keysplit voicegroupInst20, KeySplitTable43	@ fretless bass 1
	voice_keysplit voicegroupInst21, KeySplitTable113	@ fretless bass 2
	voice_keysplit voicegroupInst22, KeySplitTable95	@ slap bass
	voice_keysplit voicegroup254, KeySplitTable76	@ synth bass
	voice_keysplit voicegroupInst23, KeySplitTable60	@ strings 1
	voice_keysplit voicegroupInst24, KeySplitTable96	@ strings 2
	voice_keysplit voicegroupInst25, KeySplitTable46	@ violin
	voice_keysplit voicegroup257, KeySplitTable114	@ cello
	voice_keysplit voicegroupInst26, KeySplitTable48	@ pizzicato
	voice_keysplit voicegroupInst27, KeySplitTable115	@ harp 2
	voice_keysplit voicegroupInst28, KeySplitTable111	@ harp 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst29, KeySplitTable61	@ timpani
	voice_keysplit voicegroupInst30, KeySplitTable39	@ trumpets
	voice_keysplit voicegroupInst31, KeySplitTable47	@ trombones
	voice_keysplit voicegroupInst32, KeySplitTable116	@ solo french horn
	voice_keysplit voicegroupInst33, KeySplitTable41	@ french horns
	voice_keysplit voicegroupInst34, KeySplitTable22	@ tuba
	voice_keysplit voicegroupInst35, KeySplitTable46	@ oboe
	voice_keysplit voicegroupInst36, KeySplitTable52	@ clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst37, KeySplitTable88	@ flute 2
	voice_keysplit voicegroupInst38, KeySplitTable66	@ flute 1
	voice_keysplit voicegroupInst39, KeySplitTable117	@ bassoon
	voice_keysplit voicegroupInst40, KeySplitTable79	@ saxophone
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_bw_orch_hit_c5, 255, 250, 2, 208	@ 127/ 70/ 10/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_orch_hit_maj_c4, 255, 0, 255, 208	@ 127/127/127/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_orch_hit_min_c4, 255, 0, 255, 208	@ 127/127/127/116/ 64
	voice_keysplit voicegroupInst41, KeySplitTable118	@ choir aahs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst42, KeySplitTable38	@ square wave
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit voicegroupInst43, KeySplitTable81	@ sitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_keysplit_all voicegroupDrum1	@ standard kit
	voice_keysplit_all voicegroupDrum2	@ tr-909 kit
	voice_keysplit_all voicegroupDrum3	@ room kit
	voice_keysplit_all voicegroupDrum4	@ taiko kit
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0	@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0	@ 126/100/ 40/127/ 64
