	.align 2
voicegroupDrum6:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 60, 64, DirectSoundWaveData_bw_psp_analog_kick_c2, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_psp_analog_kick_b1, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_psp_analog_kick_b1, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_psp_analog_snare_d2, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_psp_analog_snare_d2, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_psp_analog_snare_e2, 255, 225, 127, 208	@ 127/114/ 90/116/ 64
