	.align 2
voicegroupDrum2:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 65, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 66, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 67, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 68, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 69, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 70, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 71, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 72, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 73, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 74, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 75, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 76, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_hg_033orccym, 255, 249, 0, 216	@ 127/ 80/  0/114/ 64
