	.align 2
voicegroupDrum7:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 60, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_room_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_room_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_room_snare, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80	@ not used
	voice_directsound 63, 80, DirectSoundWaveData_bw_room_closed_hihat, 255, 222, 0, 208	@ 127/115/  0/116/ 80	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 63, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 64, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 65, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 66, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 67, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 68, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 69, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 70, 80, DirectSoundWaveData_bw_room_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 60, 40, DirectSoundWaveData_bw_room_crash_cymbal, 255, 251, 0, 208	@ 127/ 62/  0/116/ 40
