	.align 2
voicegroupDrum3:: @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0		@ dummy
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 227, 178	@   3/127/120/120/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_drum_roll, 255, 0, 227, 88	@ 127/127/120/124/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 62, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_dp_sne2_loop, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_bw_drum_loop_hof, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 61, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 63, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 64, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 65, 64, DirectSoundWaveData_bw_t9_kick, 255, 0, 227, 208	@ 127/127/120/116/ 64	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80	@ not used
	voice_directsound 62, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80	@ not used
	voice_directsound 63, 80, DirectSoundWaveData_bw_909_closed_hihat, 255, 239, 0, 208	@ 127/105/  0/116/ 80	@ not used
	voice_directsound 60, 80, DirectSoundWaveData_bw_909_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80
	voice_directsound 61, 80, DirectSoundWaveData_bw_909_open_hihat, 255, 241, 0, 208	@ 127/102/  0/116/ 80	@ not used
	voice_directsound 60, 64, DirectSoundWaveData_hg_033orccym, 255, 250, 0, 216	@ 127/ 70/  0/114/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_909_crash_cymbal, 255, 242, 0, 208	@ 127/100/  0/116/ 64
