gText_ApprenticeChallenge0::
	.string "Um, I'm {STR_VAR_1}'s no. {STR_VAR_2} apprentice.\n"
	.string "Snivel… This tension is getting to me…$"

gText_ApprenticePleaseTeach0::
	.string "Are you… {PLAYER}?\n"
	.string "Oh! Sniff…sob…\p"
	.string "Oh! S-sorry…\n"
	.string "I'm so nervous, I can't help crying…\p"
	.string "I'm {STR_VAR_1}, and I really look up\n"
	.string "to you, {PLAYER}.\p"
	.string "I… I had this dream of one day meeting\n"
	.string "you and asking you about POKéMON.\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Please teach me about POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… B-but…\n"
	.string "Snivel… Waaaaaaah!\p"
	.string "Please!\n"
	.string "I'm begging you, please!$"

gText_ApprenticeWhichLevelMode0::
	.string "Oh, really? You will?\n"
	.string "Awesome! Wicked! Awoooh!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Um… Then please tell me!\n"
	.string "It's about the BATTLE TOWER.\p"
	.string "Which would be better for me: Level 50\n"
	.string "or the Open Level?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "the level for me, and it's made me cry…\p"
	.string "Snivel…\n"
	.string "Thank you so much!\l"
	.string "Please talk with me again!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sigh… Sob…\n"
	.string "Oh, {PLAYER}!\p"
	.string "I'm all tangled up in a dilemma\n"
	.string "that I can't decide.\p"
	.string "I can't decide what I should make\n"
	.string "my {STR_VAR_1} hold.\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "What item should I make it hold?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, really? I shouldn't make\n"
	.string "my {STR_VAR_1} hold anything?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, okay! I'm delighted it's settled!\n"
	.string "Awesome! Wicked! Awoooh!\p"
	.string "Thank you so much!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, I'm so glad…\n"
	.string "I think I have that {STR_VAR_1}, too.\p"
	.string "I'm delighted it's settled!\n"
	.string "Awesome! Wicked! Awoooh!\p"
	.string "Thank you so much!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaah! Please don't be mean!\p"
	.string "That item {STR_VAR_1} was already\n"
	.string "recommended to me before, sob…\p"
	.string "Or do you mean I shouldn't make\n"
	.string "my {STR_VAR_2} hold anything?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}!\n"
	.string "I have a dilemma, sob…\p"
	.string "I want to begin battling other people,\n"
	.string "but I don't know what to do.\p"
	.string "How should I line up my POKéMON\n"
	.string "so they'll be at their strongest?\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "If you were me, which of these POKéMON\l"
	.string "would you send out first?$"

gText_ApprenticeMonFirstThanks0::
	.string "My {STR_VAR_1} should go first?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry!\n"
	.string "You've made me happy by choosing\l"
	.string "my first POKéMON, and it's made me cry…\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMon0::
	.string "Snivel…\n"
	.string "Oh, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which POKéMON I should\n"
	.string "be using.\p"
	.string "I can't decide between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think will give\n"
	.string "even me a chance at winning?$"

gText_ApprenticeMonThanks0::
	.string "Snivel… I… I understand!\n"
	.string "Oh! I'm so sorry!\l"
	.string "You've made me so happy, I'm crying…\p"
	.string "I'll do my best to catch one\n"
	.string "{STR_VAR_1}!\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I'm crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Oh! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous,\n"
	.string "I can't help crying even if I win…\p"
	.string "I wish I could say something cool\n"
	.string "when I win…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you maybe teach me something\l"
	.string "cool to say when I win so I don't cry?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Awesome! Wicked! Awoooh!\n"
	.string "It's really cool!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I will battle the best I can for\n"
	.string "your sake, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… We should battle!$"
